export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_SUCCESS_WITH_WARNING = 'FETCH_TASKS_SUCCESS_WITH_WARNING';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const DELETE_TASKS_START = 'DELETE_TASKS_START';
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS';
export const DELETE_TASKS_SUCCESS_WITH_WARNING = 'DELETE_TASKS_SUCCESS_WITH_WARNING';
export const DELETE_TASKS_FAILURE = 'DELETE_TASKS_FAILURE';