export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_SUCCESS_WITH_WARNING = 'FETCH_TASKS_SUCCESS_WITH_WARNING';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const DELETE_TASKS_START = 'DELETE_TASKS_START';
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS';
export const DELETE_TASKS_SUCCESS_WITH_WARNING = 'DELETE_TASKS_SUCCESS_WITH_WARNING';
export const DELETE_TASKS_FAILURE = 'DELETE_TASKS_FAILURE';

export const EDIT_TASKS_START = 'EDIT_TASKS_START';
export const EDIT_TASKS_SUCCESS = 'EDIT_TASKS_SUCCESS';
export const EDIT_TASKS_SUCCESS_WITH_WARNING = 'EDIT_TASKS_SUCCESS_WITH_WARNING';
export const EDIT_TASKS_FAILURE = 'EDIT_TASKS_FAILURE';

export const FETCH_PROFILES_START = 'FETCH_PROFILES_START';
export const FETCH_PROFILES_SUCCESS = 'FETCH_PROFILES_SUCCESS';
export const FETCH_PROFILES_SUCCESS_WITH_WARNING = 'FETCH_PROFILES_SUCCESS_WITH_WARNING';
export const FETCH_PROFILES_FAILURE = 'FETCH_PROFILES_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_SUCCESS_WITH_WARNING = 'LOGIN_SUCCESS_WITH_WARNING';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';